baseurl = "https://crab85193.github.io/blog"
languageCode = "ja"
title = "カニのひとりごと"
theme = "charaka-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/crab85193\">Crab Anderson</a> 2021"
disqusShortname = ""
googleAnalytics = ""
publishDir = "docs"
canonifyurls = "true"

[params]
  twitterID = "@crab85193"
  description = "カニのひとりごとです。美味しいもの食べたとかプログラム作ったとか書きます。"
  images = ["default.png"]

[author]
  name = "Crab Anderson"
  homepage = "https://crab85193.github.io/blog"

[params.highlight]
  style = "zenburn"

[params.share]
  enabled = "true"

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info"

[[params.social]]
  url = "https://github.com/crab85193/"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://twitter.com/crab85193/"
  fa_icon = "fab fa-twitter"
